# Generated by Django 5.2.7 on 2025-10-26 16:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('show_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['show_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(choices=[('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=10)),
                ('number_of_tickets', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
